#pip install camelot-py
#pip install pyqt5
#pip install opencv-python
#pip install ghostscript
#and install ghostscript from: https://ghostscript.com/releases/gsdnld.html
#if code error with encoding = "utf-8" and save, please open ...site-packages\camelot\core.py
# and edit line 751 and 752:
#                table.df.to_excel(writer, sheet_name=sheet_name)
#            writer.book.save(filepath)



# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\hoclaptrinh_python\lv1\pdf2excel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QFileDialog
import sys
import os
import camelot


class Ui_MainWindow(QWidget):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 202)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("convert.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.BT_open = QtWidgets.QPushButton(self.centralwidget)
        self.BT_open.setGeometry(QtCore.QRect(40, 110, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BT_open.setFont(font)
        self.BT_open.setAutoFillBackground(False)
        icon = QtGui.QIcon.fromTheme("open")
        self.BT_open.setIcon(icon)
        self.BT_open.setObjectName("BT_open")
        self.BT_convert = QtWidgets.QPushButton(self.centralwidget)
        self.BT_convert.setGeometry(QtCore.QRect(400, 110, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BT_convert.setFont(font)
        self.BT_convert.setObjectName("BT_convert")
        self.BT_save = QtWidgets.QPushButton(self.centralwidget)
        self.BT_save.setGeometry(QtCore.QRect(220, 110, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BT_save.setFont(font)
        self.BT_save.setObjectName("BT_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
#*****************************************************************************************************************
        # PHẦN CODE THÊM VÀO
#*****************************************************************************************************************
    # NHẤP CHUỘT VÀO NÚT OPEN THÌ MỞ CỬA SỐ OPEN ĐỂ LẤY ĐƯỜNG DẪN ĐẾN FILE PDF   
        self.BT_open.clicked.connect(self.openFileNameDialog)
    # NHẤP CHUỘT VÀO NÚT SAVE THÌ MỞ CỬA SỐ SAVE ĐỂ LẤY ĐƯỜNG DẪN VÀ TÊN FILE EXCEL SAU KHI CHUYỂN         
        self.BT_save.clicked.connect(self.saveFileDialog)
    # NHẤP CHUỘT VÀO NÚT CONVERT THÌ CHUYỂN FILE PDF SANG EXCEL        
        self.BT_convert.clicked.connect(self.convert)

    # HÀM DÙNG ĐỂ LẤY ĐƯỜNG DẪN ĐẾN FILE PDF
    def openFileNameDialog(self):
        global fileSouce
        file_filter='Pdf files (*.pdf)'
        fileSouce,_= QFileDialog.getOpenFileName(parent=self,caption="Chọn tệp PDF",directory=os.getcwd(),filter=file_filter)     

    # HÀM DÙNG ĐỂ LẤY ĐƯỜNG DẪN VÀ TÊN FILE EXCCEL
    def saveFileDialog(self):
        global fileSave
        file_filter='Excel file (*.xlsx)'
        fileSave,_= QFileDialog.getSaveFileName(parent=self,caption="Lưu tệp",directory=os.getcwd(),filter=file_filter)
        if '.xlsx' not in fileSave:
            fileSave=fileSave+'.xlsx'
    # HÀM DÙNG ĐỂ CHUYỂN PDF SANG EXCEL
    def convert(self):
        try:
            tables=camelot.read_pdf(fileSouce,pages='all')
            tables.export(fileSave,f='excel',compress=False)
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Đã chuyển xong")
            msg.setInformativeText("Thành công!")
            msg.setWindowTitle("Thông báo")
            msg.exec_()
        except:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Chưa chọn file PDF hoặc chọn nơi lưu")
            msg.setInformativeText("Lỗi!")
            msg.setWindowTitle("Thông báo")
            msg.exec_()
#**************************************************************************************************************
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF2EXCEL................Code by: Trần Quốc Minh (Giáo viên Trường THPT Văn Hiến)"))
        self.label.setText(_translate("MainWindow", "Pdf to Excel"))
        self.BT_open.setText(_translate("MainWindow", "Chọn tệp PDF"))
        self.BT_convert.setText(_translate("MainWindow", "Chuyển"))
        self.BT_save.setText(_translate("MainWindow", "Chọn Nơi Lưu"))
   


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
  

